EPLF/EPLF/urls.py
# django_project/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from EPLF import views


urlpatterns = (
    [
        # path("", TemplateView.as_view(template_name="home.html"), name="home"),
        path('', login_required(views.index), name="index"),
        path("admin/", admin.site.urls),
        path("i18n/", include("django.conf.urls.i18n")),
        path("accounts/", include("accounts.urls")),
        path("managefee/", include("managefee.urls")),
        path("accounts/", include("django.contrib.auth.urls")),
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

EPLF/managefee/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .models import Subscription, CustomUser, Fee
from . import views

urlpatterns = [
    # path('', login_required(views.index), name='enroll.index'),
    path('subscriptions_list/', login_required(views.subscriptions_list), name='enroll.subscriptions_list'),
    path('subscriptions_list/create/', login_required(views.create), name="enroll.create"),
    path('subscription/plan_list/', login_required(views.plan_list), name='subscription.plan_list'),
    path('subscription/plan_create/', login_required(views.plan_create), name="subscription.plan_create"),
    path('subscription/store/', login_required(views.plan_store), name="subscription.store"),
    path('get_course_total_amount/', login_required(views.get_course_total_amount),
         name="enroll.get_course_total_amount"),
    path('subscriptions_list/store/', login_required(views.store), name="enroll.store"),
    path('sub/', login_required(views.sub), name="enroll.sub"),
    path('subscription_amount/<int:user_id>/', login_required(views.subscription_amount), name="enroll.subscription_amount"),
    path('subscriptions_list/edit/<int:eid>', login_required(views.edit), name="enroll.edit"),
    path('subscriptions_list/update/<int:eid>', login_required(views.update), name="enroll.update"),
    path('subscriptions_list/delete/<int:eid>', login_required(views.delete), name="enroll.delete"),
]

EPLF/managefee/models.py
import datetime
from django.db import models
from accounts.models import CustomUser



class Subscription(models.Model):
    
    YEAR_CHOICES = []
    for r in range(1980, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r,r))

    
    PLAN_CHOICES = (
        ("JANVIER", "janvier"),
        ("FEVRIER", "fevrier"),
        ("MARS", "mars"),
        ("AVRIL", "avril"),
        ("MAI", "mai"),
        ("JUIN", "juin"),
        ("JUILLET", "juillet"),
        ("AOUT", "aout"),
        ("SEPTEMBRE", "septembre"),
        ("OCTOBRE", "octobre"),
        ("NOVEMBRE", "novembre"),
        ("DECEMBRE", "decembre"),
    )

    plan = models.CharField(max_length=20, choices=PLAN_CHOICES)
    year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    

    def __str__(self):
        return f"{self.plan } - {self.year}"


class Fee(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
    date = models.DateField()
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f"{self.user.username} - {self.subscription.plan} - {self.subscription.year} - {self.date} - {self.amount}"

EPLF/managefee/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import Select
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker
from .models import Subscription, CustomUser, Fee
import datetime
from datetime import date

class CreateEnrollForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=CustomUser.objects.exclude(is_superuser=True), widget=forms.Select(attrs={'class': 'form-control'}), label='Locataire')
    subscription = forms.ModelChoiceField(queryset=Subscription.objects.none(), widget=forms.Select(attrs={'class': 'form-control'}), label='Abonnement')
    date = forms.DateField(widget=DatePicker(options={'useCurrent': True,'collapse': False,},attrs={'append': 'fa fa-calendar','icon_toggle': True,}), label='Date')
    amount = forms.DecimalField(label="Charge", widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))

    class Meta:
        model = Fee
        fields = ['user', 'subscription', 'date', 'amount']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subscription'].queryset = Subscription.objects.none()

        # Initialiser la date avec la date actuelle
        self.fields['date'].initial = date.today()

        if 'user' in self.data:
            self.fields['subscription'].queryset = self.get_remaining_subscriptions(self['user'].value())

    def get_remaining_subscriptions(self, user_id):
        user = CustomUser.objects.get(pk=user_id)
        enrolled_subscriptions = Fee.objects.filter(user=user).values_list('subscription', flat=True)
        return Subscription.objects.exclude(pk__in=enrolled_subscriptions)


class CreatePlanSubForm(forms.ModelForm):
    plan = forms.ChoiceField(label='Plan', choices=Subscription.PLAN_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Subscription
        fields = ['year', 'plan']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Dynamiquement définir les options pour l'année lors de la création du formulaire
        self.fields['year'] = forms.ChoiceField(
            choices=self.get_year_choices(),
            initial=datetime.datetime.now().year,  # Définir l'année actuelle comme valeur par défaut
            widget=forms.Select(attrs={'class': 'form-control'}),
            label='Année'
        )

    def get_year_choices(self):
        # Définir dynamiquement les options pour l'année en fonction de l'année actuelle
        return [(r, r) for r in range(2020, datetime.datetime.now().year + 1)]

    def clean(self):
        cleaned_data = super().clean()
        year = cleaned_data.get('year')
        plan = cleaned_data.get('plan')
        if Subscription.objects.filter(year=year, plan=plan).exists():
            raise ValidationError("Un abonnement avec ce plan existe déjà pour cette année.")
        return cleaned_data

EPLF/managefee/views.py
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from .models import Subscription, CustomUser, Fee
from managefee.forms import CreateEnrollForm, CreatePlanSubForm

# Create your views here.


# def index(request):
#     enrolls = Fee.objects.all()
#     return render(request, 'managefee/index.html', {'enrolls': enrolls})

def subscriptions_list(request):
    enrolls = Fee.objects.all()
    return render(request, 'managefee/subscriptions_list.html', {'enrolls': enrolls})

def plan_list(request):
    allSubscription = Subscription.objects.all()
    return render(request, 'managefee/plan_list.html', {'allSubscription': allSubscription})


def create(request):
    form = CreateEnrollForm()
    return render(request, 'managefee/create.html', {'form': form})

def plan_create(request):
    form = CreatePlanSubForm()
    return render(request, 'managefee/plan_create.html', {'form': form})

def plan_store(request):
    if request.method == 'POST':
        form = CreatePlanSubForm(request.POST or None)
        
        if form.is_valid():
            # print("tesssssssssst")
            # print(form)
            form.save()
            messages.success(request, 'Ce plan à bien étais enregistrer')
            return redirect('subscription.plan_list')
        else:
            return render(request, 'managefee/plan_create.html', {'form': form})
    else:
        return redirect('subscription.plan_list')



def get_course_total_amount(request):
    # print("request")
    # print(request.__dict__)
    user = CustomUser.objects.get(id=request.POST.get('course_id'))
    # print("user.feecharge")
    # print(user.feecharge)
    return JsonResponse({'data': user.feecharge})

def subscription_amount(request, user_id):
    print('request_id_js')
    print(request)
    # print(user_id)
    # user_id = request.GET.get('user_id')
    # print('user_id_js')
    print(user_id)
    if user_id:
        user = CustomUser.objects.get(id=user_id)
        feecharge = user.feecharge
        return JsonResponse({'feecharge': feecharge})
    else:
        return JsonResponse({'error': 'User ID not provided'})

def sub(request):
    form = CreateEnrollForm(request.GET)
    print(form['subscription'])
    return HttpResponse(form['subscription'])    


def store(request):
    # user = Fee.objects.get(id=request.POST.get('user'))
    # print("user")
    # print(user)
    if request.method == 'POST':
        form = CreateEnrollForm(request.POST or None)
        print("request.POST")
        print(request.POST)
        if form.is_valid():
            # print("tesssssssssst")
            # print(form)
            form.save()
            messages.success(request, 'Charge for user successfully store')
            return redirect('enroll.subscriptions_list')
        else:
            return render(request, 'managefee/create.html', {'form': form})
    else:
        return redirect('enroll.subscriptions_list')


def edit(request, eid):
    try:
        enroll = Fee.objects.get(id=eid)
        form = CreateEnrollForm(instance=enroll)
        return render(request, 'managefee/edit.html', {'form': form, 'enroll': enroll})
    except Fee.DoesNotExist:
        return redirect('enroll.subscriptions_list')


def update(request, eid):
    try:
        if request.method == 'POST':
            enroll = Fee.objects.get(id=eid)
            form = CreateEnrollForm(request.POST, instance=enroll)
            if form.is_valid():
                form.save()
                messages.success(request, 'info for user successfully updated ')
                return redirect('enroll.subscriptions_list')
            else:
                return render(request, 'managefee/edit.html', {'form': form, 'enroll': enroll})
        else:
            return redirect('enroll.subscriptions_list')
    except Fee.DoesNotExist:
        return redirect('enroll.subscriptions_list')


def delete(request, eid):
    if request.method == 'POST':
        try:
            enroll = Fee.objects.get(id=eid)
            enroll.delete()
            return redirect('enroll.subscriptions_list')
        except Fee.DoesNotExist:
            messages.error(request, 'Enrolled info not found')
            return redirect('enroll.subscriptions_list')
    else:
        messages.error(request, 'Invalid request')
        return redirect('enroll.subscriptions_list')

EPLF/templates/managefee/create.html
{% extends 'master.html' %}
{% load static %}
<script src="{% static 'js/htmx.min.js' %}" defer></script>
{% load widget_tweaks %}

{% block style %}
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'vendor/select2/select2-bootstrap4.min.css' %}">
{% endblock %}

{% block heading %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
{#        <h1 class="h3 mb-0 text-gray-800">Registration</h1>#}
        <a href="{% url 'enroll.subscriptions_list' %}" class="btn btn-danger btn-icon-split btn-sm">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-circle-left"></i>
            </span>
            <span class="text">Annuler</span>
        </a>

        <a href="javascript:void(0)" onclick="$('#enroll-form').submit()" class="btn btn-primary btn-icon-split btn-sm">
            <span class="icon text-white-50">
                <i class="fas fa-save"></i>
            </span>
            <span class="text">Payer</span>
        </a>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <!-- Area Chart -->
        <div class="col-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary text-uppercase">Ajout d'un paiement</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <form action="{% url 'enroll.store' %}" method="post" id="enroll-form">
                        {% csrf_token %}
                        {% for non_field_error in form.non_field_errors %}
                            <div class="invalid-feedback d-block">
                                {{ non_field_error }}
                            </div>
                        {% endfor %}
                        <!-- {% for fields in form %}
                            <div class="form-group">
                                <label for="{{ fields.id_for_label }}" class="text-capitalize">{{ fields.label }}</label>
                                {{ fields }}
                                {% for error in fields.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %} -->            
                        {{ form.user.label_tag }}
                        {% render_field form.user class='custom-select mb-4' autocomplete="off" hx-get="/managefee/sub/" hx-target="#id_subscription" %}


                        {{ form.subscription.label_tag }}
                        {% render_field form.subscription class='custom-select mb-4' %}

                        {{ form.date.label_tag }}
                        {% render_field form.date class='custom-select mb-4' %}

                        {{ form.amount.label_tag }}
                        {% render_field form.amount|append_attr:"readonly:readonly" type="text" placeholder="Charge"  class='custom-select mb-4' %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    
    {% comment %} <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(function () {
            $('select').each(function () {
                $(this).select2({
                    theme: 'bootstrap4',
                    placeholder: '---',
                });
            });

            $('#id_user').on('change', function () {
                let user = $(this).val();
                get_total_amount("{% url 'enroll.get_course_total_amount' %}", user);
                console.log(user)
            });
        });
    </script> {% endcomment %}
    {% comment %} <script>
        const userSelect = document.getElementById('id_user');
        console.log(userSelect);
        const amountInput = document.getElementById('id_amount');
        console.log(amountInput);
        const endpointUrl = "{% url 'enroll.subscription_amount' %}";

        userSelect.addEventListener('change', () => {
            const userId = userSelect.value;
            const url = endpointUrl.replace('0', userId);
            fetch(url)
            .then(response => response.json())
            .then(feecharge => {
                const amount = feecharge['feecharge'];
                console.log(amount);
                amountInput.value = amount;
            })
            .catch(error => {
                console.error(error);
            });
        });
    </script> {% endcomment %}

    <script>
        function getSelectValue(selectId){
        /**On récupère l'élement html <select>*/
        var selectElmt = document.getElementById(selectId);
        /**
        selectElmt.options correspond au tableau des balises <option> du select
        selectElmt.selectedIndex correspond à l'index du tableau options qui est actuellement sélectionné
        */
        return selectElmt.options[selectElmt.selectedIndex].value;
}
        const userSelect = document.getElementById('id_user');
        userSelect.addEventListener('change', () => {
        var selectValue = getSelectValue('id_user');
        console.log(selectValue)
        let csrfTokenValue = document.querySelector('[name=csrfmiddlewaretoken]').value;

        const url = "{% url 'enroll.subscription_amount' 0 %}".replace("0", selectValue);

        const request = new Request(url);
        console.log(request);
        fetch(request)
            .then(response => response.json())
            .then(feecharge => {
                console.log(feecharge);
                document.getElementById("id_amount").value = feecharge.feecharge;
            })
})

    </script>
{% endblock %}

EPLF/templates/managefee/edit.html
{% extends 'master.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'vendor/select2/select2-bootstrap4.min.css' %}">
{% endblock %}

{% block heading %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
{#        <h1 class="h3 mb-0 text-gray-800">Registration</h1>#}
        <a href="{% url 'enroll.subscriptions_list' %}" class="btn btn-danger btn-icon-split btn-sm">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-circle-left"></i>
            </span>
            <span class="text">Cancel</span>
        </a>

        <a href="javascript:void(0)" onclick="$('#enroll-form').submit()" class="btn btn-primary btn-icon-split btn-sm">
            <span class="icon text-white-50">
                <i class="fas fa-save"></i>
            </span>
            <span class="text">Insert</span>
        </a>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <!-- Area Chart -->
        <div class="col-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary text-uppercase">Edit Record</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <form action="{% url 'enroll.update' eid=form.instance.id %}" method="post" id="enroll-form">
                        {% csrf_token %}
                        {% for non_field_error in form.non_field_errors %}
                            <div class="invalid-feedback d-block">
                                {{ non_field_error }}
                            </div>
                        {% endfor %}
                        {% for fields in form %}
                            <div class="form-group">
                                <label for="{{ fields.id_for_label }}" class="text-capitalize">{{ fields.label }}</label>
                                {{ fields }}
                                {% for error in fields.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(function () {
            $('select').each(function () {
                $(this).select2({
                    theme: 'bootstrap4',
                    placeholder: '---',
                });
            });

            $('#id_course_id').on('change', function () {
                let course_id = $(this).val();
                get_total_amount("{% url 'enroll.get_course_total_amount' %}", course_id);
            });
        });
    </script>
{% endblock %}

EPLF/templates/managefee/plan_create.html
{% extends 'master.html' %}
{% load static %}
<script src="{% static 'js/htmx.min.js' %}" defer></script>
{% load widget_tweaks %}

{% block style %}
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'vendor/select2/select2-bootstrap4.min.css' %}">
{% endblock %}

{% block heading %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
{#        <h1 class="h3 mb-0 text-gray-800">Registration</h1>#}
        <a href="{% url 'enroll.subscriptions_list' %}" class="btn btn-danger btn-icon-split btn-sm">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-circle-left"></i>
            </span>
            <span class="text">Annuler</span>
        </a>

        <a href="javascript:void(0)" onclick="$('#enroll-form').submit()" class="btn btn-primary btn-icon-split btn-sm">
            <span class="icon text-white-50">
                <i class="fas fa-save"></i>
            </span>
            <span class="text">Ajouter</span>
        </a>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <!-- Area Chart -->
        <div class="col-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary text-uppercase">Creation d'un Plan</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <form action="{% url 'subscription.store' %}" method="post" id="enroll-form">
                        {% csrf_token %}
                        {% for non_field_error in form.non_field_errors %}
                            <div class="invalid-feedback d-block">
                                {{ non_field_error }}
                            </div>
                        {% endfor %}
                        {% for fields in form %}
                            <div class="form-group">
                                <label for="{{ fields.id_for_label }}" class="text-capitalize">{{ fields.label }}</label>
                                {{ fields }}
                                {% for error in fields.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}      
                  
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    
    {% comment %} <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(function () {
            $('select').each(function () {
                $(this).select2({
                    theme: 'bootstrap4',
                    placeholder: '---',
                });
            });

            $('#id_user').on('change', function () {
                let user = $(this).val();
                get_total_amount("{% url 'enroll.get_course_total_amount' %}", user);
                console.log(user)
            });
        });
    </script> {% endcomment %}
    {% comment %} <script>
        const userSelect = document.getElementById('id_user');
        console.log(userSelect);
        const amountInput = document.getElementById('id_amount');
        console.log(amountInput);
        const endpointUrl = "{% url 'enroll.subscription_amount' %}";

        userSelect.addEventListener('change', () => {
            const userId = userSelect.value;
            const url = endpointUrl.replace('0', userId);
            fetch(url)
            .then(response => response.json())
            .then(feecharge => {
                const amount = feecharge['feecharge'];
                console.log(amount);
                amountInput.value = amount;
            })
            .catch(error => {
                console.error(error);
            });
        });
    </script> {% endcomment %}

        {% comment %} <script>
            function getSelectValue(selectId){
            /**On récupère l'élement html <select>*/
            var selectElmt = document.getElementById(selectId);
            /**
            selectElmt.options correspond au tableau des balises <option> du select
            selectElmt.selectedIndex correspond à l'index du tableau options qui est actuellement sélectionné
            */
            return selectElmt.options[selectElmt.selectedIndex].value;
    }
            const userSelect = document.getElementById('id_user');
            userSelect.addEventListener('change', () => {
            var selectValue = getSelectValue('id_user');
            console.log(selectValue)
            let csrfTokenValue = document.querySelector('[name=csrfmiddlewaretoken]').value;

            const url = "{% url 'enroll.subscription_amount' 0 %}".replace("0", selectValue);

            const request = new Request(url);
            console.log(request);
            fetch(request)
                .then(response => response.json())
                .then(feecharge => {
                    console.log(feecharge);
                    document.getElementById("id_amount").value = feecharge.feecharge;
                })
    })

        </script> {% endcomment %}
{% endblock %}

EPLF/templates/managefee/plan_list.html
{% extends 'master.html' %}
{% load static %}

{% block style %}
    <link href="{% static "vendor/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet">
{% endblock %}

{% block heading %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            <i class="fas fa-fw fa-school"></i>
        </h1>

        <a href="{% url 'subscription.plan_create' %}" class="btn btn-success btn-icon-split btn-sm">
            <span class="icon text-white-50">
                <i class="fas fa-plus-circle"></i>
            </span>
            <span class="text">Créer un plan</span>
        </a>
    </div>
    {% include 'messages.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Liste des Plans d'abonnements</h6>
                </div>

                <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Plan</th>
                                <th>Année</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Plan</th>
                                <th>Année</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for Subscription in allSubscription %}
                                <tr>
                                    <td>{{ Subscription.id }}</td>
                                    <td>{{ Subscription.plan }}</td>
                                    <td>{{ Subscription.year }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>
    <script>
        $('#dataTable').dataTable( {
          "columnDefs": [
            { "width": "20%", "targets": 1 }
          ], 
          "pageLength": 8,
          "order": [[ 0, "asc" ]]
        });
    </script>
{% endblock %}